---
- name: Install nodes dependencies
  hosts: nodes
  become: true
  gather_facts: false  
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Java OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install wget
      apt:
        name: wget
        state: present

    - name: Install gnupg
      apt:
        name: gnupg
        state: present

    - name: Add GPG key for scala.jfrog.io repository
      apt_key:
        url: "https://scala.jfrog.io/artifactory/api/gpg/key/public"
        state: present

    - name: Add sbt repository
      apt_repository:
        repo: "deb https://repo.scala-sbt.org/scalasbt/debian all main"
        state: present
        filename: sbt

    - name: Add sbt old repository
      apt_repository:
        repo: "deb https://repo.scala-sbt.org/scalasbt/debian /"
        state: present
        filename: sbt_old

    - name: Add sbt public key
      apt_key:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823"
        state: present

    - name: Install sbt
      apt:
        name: sbt
        state: present