---
- name: (Lead) Get the first node
  vars:
    all_nodes: "{{ lookup('env', 'NODES') }}"
  set_fact:
    node_info: "{{ all_nodes[0] }}"  

- name: (Lead) Get lead node info
  community.docker.docker_container_exec:
    container: "{{ node_info.name }}"
    command: "bash -c 'cd global-l0 && java -jar cl-wallet.jar show-id'"
    env:
      CL_KEYSTORE: "{{ node_info.key_file.name }}"
      CL_KEYALIAS: "{{ node_info.key_file.alias }}"
      CL_PASSWORD: "{{ node_info.key_file.password }}"
  register: node_id

- set_fact:
    lead_node_id: "{{ node_id.stdout  }}"