---
- name: (Monitoring) Stop Monitoring
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../../vars.ansible.yml
  tasks:
    - name: (Monitoring) Stopping monitoring
      shell: |
       cd {{ lookup('env', 'INFRA_PATH') }}/docker/grafana
       {{ lookup('env', 'DOCKER_COMPOSE') }} down