---
- name: (Metagraph-L0) Getting nodes info
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../../vars.ansible.yml
  tasks:
    - name: (Metagraph-L0) Getting lead node information
      include_tasks: ../shared/get-lead-node-info.ansible.yml


- name: (Metagraph-L0) Genesis
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../../vars.ansible.yml
  vars:
    all_nodes: "{{ lookup('env', 'NODES') }}"
  tasks:
    - name: (Metagraph-L0) Check execution type
      set_fact:
        force_genesis_bool: "{{ force_genesis | default(true) | bool }}"
      
    - name: (Metagraph-L0) Get the first node
      set_fact:
        first_node_info: "{{ all_nodes[0] }}"

    - name: (Metagraph-L0) Run genesis
      include_tasks: genesis.ansible.yml
      vars:
        node_info: "{{ first_node_info }}"
      when: force_genesis_bool

    - name: (Metagraph-L0) Run rollback
      include_tasks: rollback.ansible.yml
      vars:
        node_info: "{{ first_node_info }}"
      when: not force_genesis_bool

- name: (Metagraph-L0) Starting the validators
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../../vars.ansible.yml
  vars:
    all_nodes: "{{ lookup('env', 'NODES') }}"
  tasks:
    - name: (Metagraph-L0) Starting Validator
      include_tasks: validator.ansible.yml
      loop: "{{ all_nodes[1:] }}"
      loop_control:
        loop_var: validator_node_info
        index_var: index
      no_log: true