version: '3'
services:
  metagraph-base-image:
    platform: linux/amd64
    image: "metagraph-base-image"
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-base-image/Dockerfile