---
- name: Check execution type
  set_fact:
    force_genesis_bool: "{{ force_genesis | default(true) | bool }}"

- name: Get current timestamp
  set_fact:
    current_time: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S%z') }}"
  when: force_genesis_bool

- name: Ensure archived-data directory exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/code/metagraph-l0/archived-data
    state: directory
  when: force_genesis_bool

- name: Save previous data directory
  shell: |
    cd "/home/{{ ansible_user }}/code/metagraph-l0"
    mv data archived-data/data_{{ current_time }}
  ignore_errors: true
  when: force_genesis_bool

- name: Check if metagraph-l0.jar exists
  stat:
    path: "/home/{{ ansible_user }}/code/metagraph-l0/metagraph-l0.jar"
  register: metagraph_l0_jar

- name: Throw an error if the file metagraph-l0.jar doesn't exist
  fail:
    msg: "File /home/{{ ansible_user }}/code/metagraph-l0/metagraph-l0.jar does not exist"
  when: not metagraph_l0_jar.stat.exists
     
- name: Check if token file exists
  stat:
    path: "/home/{{ ansible_user }}/code/metagraph-l0/{{ cl_keystore }}"
  register: token_file

- name: Throw an error if the token_file doesn't exist
  fail:
    msg: "File /home/{{ ansible_user }}/code/metagraph-l0/{{ cl_keystore }} does not exist"
  when: not token_file.stat.exists

- name: Check if we already have incremental snapshots
  stat:
    path: "/home/{{ ansible_user }}/code/metagraph-l0/data/incremental_snapshot"
  register: folder_exists

- name: Start as rollback
  environment:
    CL_PUBLIC_HTTP_PORT: "{{ base_metagraph_l0_public_port }}"
    CL_P2P_HTTP_PORT: "{{ base_metagraph_l0_p2p_port }}"
    CL_CLI_HTTP_PORT: "{{ base_metagraph_l0_cli_port }}"

    CL_GLOBAL_L0_PEER_HTTP_HOST: "{{ gl0_ip }}"
    CL_GLOBAL_L0_PEER_HTTP_PORT: "{{ gl0_port }}"
    CL_GLOBAL_L0_PEER_ID: "{{ gl0_id }}"

    CL_KEYSTORE: "{{ cl_keystore }}"
    CL_KEYALIAS: "{{ cl_keyalias }}"
    CL_PASSWORD: "{{ cl_password }}"
    
    CL_APP_ENV: "{{ network }}"
    CL_COLLATERAL: 0
    CL_L0_TOKEN_IDENTIFIER: "{{ metagraph_id }}"
  shell: |
    cd "/home/{{ ansible_user }}/code/metagraph-l0"
    nohup java -jar metagraph-l0.jar run-rollback --ip {{ ansible_host }} > metagraph-l0.log 2>&1 &
  when: folder_exists.stat.exists and not force_genesis_bool

- name: Start as genesis
  environment:
    CL_PUBLIC_HTTP_PORT: "{{ base_metagraph_l0_public_port }}"
    CL_P2P_HTTP_PORT: "{{ base_metagraph_l0_p2p_port }}"
    CL_CLI_HTTP_PORT: "{{ base_metagraph_l0_cli_port }}"

    CL_GLOBAL_L0_PEER_HTTP_HOST: "{{ gl0_ip }}"
    CL_GLOBAL_L0_PEER_HTTP_PORT: "{{ gl0_port }}"
    CL_GLOBAL_L0_PEER_ID: "{{ gl0_id }}"

    CL_KEYSTORE: "{{ cl_keystore }}"
    CL_KEYALIAS: "{{ cl_keyalias }}"
    CL_PASSWORD: "{{ cl_password }}"
    
    CL_APP_ENV: "{{ network }}"
    CL_COLLATERAL: 0
  shell: |
    cd /home/{{ ansible_user }}/code/metagraph-l0
    nohup java -jar metagraph-l0.jar run-genesis genesis.snapshot --ip {{ ansible_host }} > metagraph-l0.log 2>&1 &
  when: not folder_exists.stat.exists or force_genesis_bool

- name: Check if node is Ready
  uri:
    url: "http://localhost:{{ base_metagraph_l0_public_port }}/node/info"
    method: GET
    return_content: yes
  register: response
  until: response.status == 200 and ("Ready" in response.content | string or retries >= 100)
  retries: 120
  delay: 1
  vars:
    retries: 0