# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  l0-currency-2:
    container_name: l0-currency-2
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l0/node-2/Dockerfile
    image: metagraph-l0-validator-node-2
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '9500:9000'
      - '9501:9001'
      - '9502:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.21
    command: >
      sh -c "cp jars/cl-wallet.jar genesis/cl-wallet.jar && \

             cd genesis/ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_GENESIS} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_GENESIS} && \
             export CL_PASSWORD=$${CL_PASSWORD_GENESIS} && \

             export CL_GLOBAL_L0_PEER_ID=$$(java -jar cl-wallet.jar show-id) && \
             export CL_L0_TOKEN_IDENTIFIER=$METAGRAPH_ID && \

             cd ../ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_NODE_2} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_NODE_2} && \
             export CL_PASSWORD=$${CL_PASSWORD_NODE_2} && \

             cp jars/metagraph-l0.jar metagraph-l0.jar && \
             java -jar metagraph-l0.jar run-validator --ip 172.50.0.21"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l0-currency-2:9000/metrics" ]
      interval: 10s
      timeout: 10s
      retries: 10
  l0-currency-3:
    container_name: l0-currency-3
    build:
      context: ../../../source
      dockerfile: ../infra/docker/metagraph-l0/node-3/Dockerfile
    image: metagraph-l0-validator-node-3
    environment:
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
    volumes:
      - ../shared/jars:/code/jars/
    ports:
      - '9600:9000'
      - '9601:9001'
      - '9602:9002'
    networks:
      custom-network:
        ipv4_address: 172.50.0.22
    command: >
      sh -c "cp jars/cl-wallet.jar genesis/cl-wallet.jar && \

             cd genesis/ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_GENESIS} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_GENESIS} && \
             export CL_PASSWORD=$${CL_PASSWORD_GENESIS} && \

             export CL_GLOBAL_L0_PEER_ID=$$(java -jar cl-wallet.jar show-id) && \
             export CL_L0_TOKEN_IDENTIFIER=$METAGRAPH_ID && \

             cd ../ && \

             export CL_KEYSTORE=$${CL_KEYSTORE_NODE_3} && \
             export CL_KEYALIAS=$${CL_KEYALIAS_NODE_3} && \
             export CL_PASSWORD=$${CL_PASSWORD_NODE_3} && \

             cp jars/metagraph-l0.jar metagraph-l0.jar && \
             java -jar metagraph-l0.jar run-validator --ip 172.50.0.22"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l0-currency-3:9000/metrics" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true