---
- name: Install dependencies
  hosts: localhost
  connection: local
  vars_files:
    - ../../vars.ansible.yml
  tasks:
  - name: Check if pip3 is installed
    shell: command -v pip3
    register: pip3_installed
    ignore_errors: yes
    changed_when: false

  - name: Install pip3 on Debian/Ubuntu
    apt:
      name: python3-pip
      state: present
    when:
      - ansible_os_family == "Debian"
      - pip3_installed.rc != 0
    become: true

  - name: Install pip3 on macOS
    homebrew:
      name: python3
      state: present
    when:
      - ansible_os_family == "Darwin"
      - pip3_installed.rc != 0
    become: no

  - name: Install requests module
    pip:
      name: requests
      state: present

  - name: Check if community.docker collection is installed
    stat:
      path: "$HOME/.ansible/collections/ansible_collections/community/docker"
    register: collection_status

  - name: Install community.docker collection if not installed
    ansible.builtin.command:
      cmd: ansible-galaxy collection install community.docker --force
    when: not collection_status.stat.exists

- name: Start Docker containers
  hosts: localhost
  connection: local
  vars_files:
    - ../../vars.ansible.yml
  tasks:
    - name: Get all nodes from euclid.json
      set_fact:
        all_nodes: "{{ lookup('env', 'NODES') }}"

    - name: Create custom network
      docker_network:
        name: custom-network
        driver: bridge
        ipam_config:
          - subnet: 172.50.0.0/24

    - name: Starting Docker container
      docker_container:
        name: "{{ node_info.name }}"
        image: metagraph-base-image:latest
        state: started
        networks:
        - name: custom-network
          ipv4_address: "{{ base_prefix_ip }}{{ (index + 1) * offset }}"
        volumes:
          - "{{ lookup('env', 'INFRA_PATH') }}/docker/shared/genesis:/code/shared_genesis"
          - "{{ lookup('env', 'INFRA_PATH') }}/docker/shared/jars:/code/shared_jars"
        ports:
          - "{{ (base_global_l0_public_port | int ) +  (offset * index) }}:{{ (base_global_l0_public_port | int ) + (offset * index) }}"
          - "{{ (base_global_l0_p2p_port | int ) +  (offset * index) }}:{{ (base_global_l0_p2p_port | int ) + (offset * index) }}"
          - "{{ (base_global_l0_cli_port | int ) +  (offset * index) }}:{{ (base_global_l0_cli_port | int ) + (offset * index) }}"

          - "{{ (base_dag_l1_public_port | int ) +  (offset * index) }}:{{ (base_dag_l1_public_port | int ) + (offset * index) }}"
          - "{{ (base_dag_l1_p2p_port | int ) +  (offset * index) }}:{{ (base_dag_l1_p2p_port | int ) + (offset * index) }}"
          - "{{ (base_dag_l1_cli_port | int ) +  (offset * index) }}:{{ (base_dag_l1_cli_port | int ) + (offset * index) }}"

          - "{{ (base_metagraph_l0_public_port | int ) +  (offset * index) }}:{{ (base_metagraph_l0_public_port | int ) + (offset * index) }}"
          - "{{ (base_metagraph_l0_p2p_port | int ) +  (offset * index) }}:{{ (base_metagraph_l0_p2p_port | int ) + (offset * index) }}"
          - "{{ (base_metagraph_l0_cli_port | int ) +  (offset * index) }}:{{ (base_metagraph_l0_cli_port | int ) + (offset * index) }}"

          - "{{ (base_currency_l1_public_port | int ) +  (offset * index) }}:{{ (base_currency_l1_public_port | int ) + (offset * index) }}"
          - "{{ (base_currency_l1_p2p_port | int ) +  (offset * index) }}:{{ (base_currency_l1_p2p_port | int ) + (offset * index) }}"
          - "{{ (base_currency_l1_cli_port | int ) +  (offset * index) }}:{{ (base_currency_l1_cli_port | int ) + (offset * index) }}"

          - "{{ (base_data_l1_public_port | int ) +  (offset * index) }}:{{ (base_data_l1_public_port | int ) + (offset * index) }}"
          - "{{ (base_data_l1_p2p_port | int ) +  (offset * index) }}:{{ (base_data_l1_p2p_port | int ) + (offset * index) }}"
          - "{{ (base_data_l1_cli_port | int ) +  (offset * index) }}:{{ (base_data_l1_cli_port | int ) + (offset * index) }}"
      loop: "{{ all_nodes }}"
      loop_control:
        loop_var: node_info
        index_var: index
      no_log: true