#!/bin/bash
BASEDIR=$(dirname "$0")
cd $BASEDIR

echo "Please provide your GITHUB_TOKEN:"
read github_token

if [ -z "$github_token" ]
then
  echo "You should provide the GITHUB_PERSONAL_TOKEN"
else
  cd ..
  chmod -R +w images
  export DOCKER_BUILDKIT=0
  docker network create --driver=bridge --subnet=172.50.0.0/24 custom-network
  git clone https://github.com/Constellation-Labs/tessellation.git
  mv tessellation/ images/currency-l0

  cd composes/shared || exit
  docker-compose build
  docker-compose up -d
  cd ../../

  cd composes/currency-l0 || exit
  docker-compose build --build-arg GIT_PERSONAL_ACCESS_TOKEN=$github_token
  docker-compose up -d
  cd ../../
fi