#!/bin/bash
BASEDIR=$(dirname "$0")
cd $BASEDIR

chmod -R +w images

cd images ||  exit

rm -r currency-l1/initial-validator/tessellation
rm -r currency-l1/validators/tessellation
cd ../

cd composes/currency-l1 || exit
docker-compose  down --remove-orphans
cd ../../