{
 "title": "SDK - Global Layer Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(process_uptime_seconds{application=~\"$application\"}, ip)"
    }
   },
   {
    "name": "peer_id",
    "label": "PeerId",
    "query": {
     "query": "label_values(process_uptime_seconds{application=~\"$application\", ip=~\"$ip\"}, peer_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global L0 - Cluster size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(process_uptime_seconds{application=\"dag-l0\"})"
    }
   ]
  },
  {
   "title": "Global L1 - Cluster size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(process_uptime_seconds{application=\"dag-l1\"})"
    }
   ]
  },
  { "title": "Health", "type": "alertlist", "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 } },
  {
   "title": "Global L0 - uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_uptime_seconds{application=\"dag-l0\"})"
    }
   ]
  },
  {
   "title": "Global L1 - uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_uptime_seconds{application=\"dag-l1\"})"
    }
   ]
  },
  { "title": "Global Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Ordinal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "dag_global_snapshot_ordinal{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\"}",
     "legendFormat": "{{peer_id_short}}"
    }
   ]
  },
  {
   "title": "Consensus duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(dag_consensus_duration_seconds_sum{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[90s])/rate(dag_consensus_duration_seconds_count{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[90s])",
     "legendFormat": "{{peer_id_short}}"
    }
   ]
  },
  {
   "title": "Active tips",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max(dag_global_snapshot_tips_count{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\", tip_type=\"active\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(dag_global_snapshot_tips_count{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\", tip_type=\"active\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Proposal affinity",
   "type": "natel-discrete-panel",
   "description": "Percent of the facilitators that proposed the same value",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(dag_consensus_proposal_affinity_sum{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[90s])/rate(dag_consensus_proposal_affinity_count{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[90s])",
     "legendFormat": "{{peer_id_short}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "max(dag_global_snapshot_transactions_total{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(dag_global_snapshot_transactions_total{ip=~\"$ip\", peer_id=~\"$peer_id\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "max(dag_global_snapshot_blocks_total{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(dag_global_snapshot_blocks_total{application=\"dag-l0\", ip=~\"$ip\", peer_id=~\"$peer_id\"})",
     "legendFormat": "Min"
    }
   ]
  },
  { "title": "Global Gossip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Rumor spreads by content type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (content_type_short) (increase(dag_rumors_spread_total{application=~\"dag-l0|dag-l1\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rumor spreads by rumor type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rumor_type) (increase(dag_rumors_spread_total{application=~\"dag-l0|dag-l1\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gossip rounds/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "increase(dag_gossip_round_succeeded_total{application=~\"dag-l0|dag-l1\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m])",
     "legendFormat": "{{peer_id_short}}"
    }
   ]
  },
  {
   "title": "Rumors spreaded/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (peer_id_short) (increase(dag_rumors_spread_total{application=~\"dag-l0|dag-l1\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]))",
     "legendFormat": "{{peer_id_short}}"
    }
   ]
  },
  {
   "title": "Rumors consumed/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (peer_id_short) (increase(dag_rumors_consumed_total{application=~\"dag-l0|dag-l1\", ip=~\"$ip\", peer_id=~\"$peer_id\"}[1m]))",
     "legendFormat": "{{peer_id_short}}"
    }
   ]
  },
  {
   "title": "Round duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(dag_gossip_round_duration_seconds_sum{application=~\"dag-l0|dag-l1\", ip=~\"$ip\", peer_id=~\"$peer_id\", round_label=\"peer\"}[30s])/rate(dag_gossip_round_duration_seconds_count{application=~\"$application\", ip=~\"$ip\", peer_id=~\"$peer_id\", round_label=\"peer\"}[30s])",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}