services:
  metagraph-ubuntu:
    build:
      context: .
      args:
        - CHECKOUT_TESSELLATION_VERSION
        - TESSELLATION_VERSION_IS_TAG_OR_BRANCH
    image: "metagraph-ubuntu-${TESSELLATION_VERSION_NAME}"
