global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: dynamic-targets
    http_sd_configs:
      - url: http://172.50.0.10:9000/targets
      - url: http://172.50.0.10:9100/targets
      - url: http://172.50.0.20:9110/targets
      - url: http://172.50.0.30:9120/targets
      - url: http://172.50.0.10:9200/targets
      - url: http://172.50.0.20:9210/targets
      - url: http://172.50.0.30:9220/targets
      - url: http://172.50.0.10:9300/targets
      - url: http://172.50.0.20:9310/targets
      - url: http://172.50.0.30:9320/targets
      - url: http://172.50.0.10:9400/targets
      - url: http://172.50.0.20:9410/targets
      - url: http://172.50.0.30:9420/targets